[package]
name = "paperboy"
authors = ["Max (mxcop)"]
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
minreq = { version = "2.7.0", features = ["https-rustls"] }
once_cell = "1.16"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
